name: PublishTWBXWorkbook
on:
  push:
    branches: [main]

env:
  UNAME: ${{secrets.USERNAME}}
  PASS: ${{secrets.PASSWORD}}
  SERVURL: ${{secrets.SERVERURL}}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.get-files.outputs.files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install tableauserverclient

      - name: Get changed twbx files
        id: get-files
        run: echo ::set-output name=files::$(git diff-tree --no-commit-id --diff-filter=AM --name-only -r $(git rev-parse HEAD) -- *.twbx -- *.twb | jq -R -s -c 'split("\n")[:-1]' | jq -r '.[] | (","+.)')

      - name: Publish twbx Workbook
        run: |
          project_id=`jq '.project_id' project-d.json`
          if [ ! "${{ steps.get-files.outputs.files }}" ];then
              echo "TWBX file list is Empty."
          else
              python3 publish_twb_workbook.py --server_url "${{env.SERVURL}}" --project_id "${project_id}" --password ${{env.PASS}} --username ${{env.UNAME}} --workbook_files "${{ steps.get-files.outputs.files }}"
          fi
