name: CI
on:
  pull_request:
    branches: [ "main" ]
jobs:  
  changedFilesList: 
    runs-on: ubuntu-latest
    outputs:
      changedfiles: ${{ steps.set-changed-files.outputs.changedfiles }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v2
      - name: Get main branch
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
      - name: Get list of changed files
        id: set-changed-files
        run: echo ::set-output name=changedfiles::$(git diff --name-only --diff-filter=AM origin/${{ github.event.pull_request.base.ref }} HEAD -- *.twbx -- *.twb | jq -R -s -c 'split("\n")[:-1]' | jq -r '.[] | ("./" + .)')
      - name: Print files to be validated
        run: |
          echo "${{steps.set-changed-files.outputs.changedfiles}}"